language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t itayturni/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true itayturni/docker-react npm run test